<?php

/**
 * @file
 * Provides batch exporting for Webform results.
 */

/**
 * Implements hook_menu().
 */
function webform_batch_menu() {
  return array(
    'node/%webform_menu/webform-results/batch_export' => array(
      'title' => 'Batch Export',
      'description' => t('Batch export webform results'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('webform_batch_form', 1),
      'access arguments' => array('access all webform results'),
      'type' => MENU_LOCAL_TASK,
      'weight' => 8,
    ),
    'admin/settings/webform/batch' => array(
      'title' => 'Webform Batch Settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('webform_batch_admin_settings_form'),
      'access arguments' => array('access all webform results'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'webform_batch.admin.inc',
    ),
  );
}

/**
 * Batch Export Form.
 */
function webform_batch_form(&$form_state, $node) {
  $submissions = db_result(db_query("SELECT COUNT(*) FROM {webform_submissions} WHERE nid = %d", $node->nid));
  
  $form['submissions'] = array(
    '#type' => 'markup',
    '#prefix' => '<div class="submissions">',
    '#suffix' => '</div>',
    '#value' => $submissions,
  );
  
  $form['number_results'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of results to export at once'),
    '#default_value' => variable_get('webform_batch_number_results', 200),
  );
  
  $form['nid'] = array(
    '#type' => 'hidden',
    '#value' => $node->nid,
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Start Batch Export'),
  );
  
  return $form;
}

/**
 * Submit Handler: Batch Export Form.
 */
function webform_batch_form_submit($form, &$form_state) {
  $batch = array(
    'operations' => array(
      array('webform_batch_export_csv', array($form_state['values']['nid'], $form_state['values']['number_results'])),
    ),
    'finished' => 'webform_batch_finished',
    'title' => t('Webform Results Batching'),
    'init_message' => t('Starting ...'),
    'error_message' => t('An error occurred and some or all of the batch has failed.'),
    'file' => drupal_get_path('module', 'webform_batch') . '/webform_batch.batch.inc',
  );
  
  batch_set($batch);  
}
